### ISSUE TITLE
More information please

### ISSUE THREAD

**Issue by staxDB** [twam/IEC-62056-21-Optical-Probe#1]
Hey there, thanks for sharing your work within this repository! I'm new to electronics and basically have no experience so far. Could you provide more information about how I can use this probe and whether it is possible to flash it like an esp? I'd like to integrate it in my smart home setup

**Comment by twam** [comment]
This probe doesn't include any microcontroller such as ESP. It just provides a standard USB serial port which spits out the data the power meter sends.
